version: "0.1.0"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: go-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env     
  frontend:
    build:
      context: ./web
      dockerfile: dockerfile
    container_name: react-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
